### ISSUE TITLE
bug: loading reference 'xx\xx\neoconf.nvim\schemas\pyright.json/': Unable to laod schema from '\'

### ISSUE THREAD

**Issue by liuyangzys** [folke/neoconf.nvim#18]
### Did you check docs and existing issues?

- [X] I have read all the neoconf.nvim docs
- [X] I have searched the existing issues of neoconf.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1115+g446c353a5

### Operating system/version

Windows 11

### Describe the bug

I opened a python file and use cmd "Neoconf local" to edit the local lsp configuration file. Then it report a bug as follow 
![image](https://user-images.githubusercontent.com/19203871/225315956-ee8a51b7-391a-45db-91f8-94fcedc4d82f.png)

### Steps To Reproduce

1. open a python file in nvim 9.0, Windows 11
2. edit the settings json file by command "Neoconf local"

### Expected Behavior

the reference json file should be found in the right path.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/neoconf.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I think I just fixed that. Would be great if you could verify

**Comment by liuyangzys** [comment]
> 

It looks like there are still some problems. I have updated neoconf.nvim to the newest version from github.
![image](https://user-images.githubusercontent.com/19203871/225483176-3f7f486e-293c-419f-8e2c-f35631152cad.png)

And I confirm that  the ”pyright.json“ file does exist. 
![image](https://user-images.githubusercontent.com/19203871/225483713-fc7846f1-fe9c-469f-9ff2-71e8a999edd3.png)

**Comment by liuyangzys** [comment]
> I think I just fixed that. Would be great if you could verify

It looks like there are still some problems. I have update neoconf.nvim to the correct head
![image](https://user-images.githubusercontent.com/19203871/225485886-70e10095-195d-4a20-8d60-3cd4f1704f04.png)

But the bug report still exist
![image](https://user-images.githubusercontent.com/19203871/225485742-77480536-299c-4959-8bbf-b61d9a538acc.png)

And I confirm that the pyright.json file does exist 
![image](https://user-images.githubusercontent.com/19203871/225486044-f4eb263b-df58-40ef-8f22-4e626cbacd1f.png)

**Comment by folke** [comment]
Can you check again with the last update?

**Comment by liuyangzys** [comment]
> 

It woks fine now! Thanks for you hard work.
